s3:
  swagger:
    bucket: 'microservice-artifacts'
    key: 'lambda/template/swagger.yaml'

composition_root_project: 'TemplateService.APIGatewayAdapter'

application_name: 'C# Template Project'

environments:
  - name: 'production'
    variables:
      verbosity: 'Info'
    description: 'Live Production Environment.'
  - name: 'test'
    variables:
      verbosity: 'Debug'
    description: 'Generic Testing environment to test deployments and whatnot.'

lambdas:
  - lambda_name: 'DotnetCoreTemplateLambda'
    handler: 'TemplateService::TemplateService.Controller::Handler'
    description: 'Dotnet Lambda Template'
    timeout: 15
    memory_size: 256
    role_arn: 'arn:aws:iam::652754698884:role/LambdaMicroservice'
    runtime: 'dotnetcore1.0'
    subnet_ids:
      - 'subnet-7a422a1e'
      - 'subnet-cce782ba'
      - 'subnet-e0a903b8'
    security_group_ids:
      - 'sg-09252c6e'
    delete_unreferenced_versions: true
