//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Implementation.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DELETE FROM Product
        ///WHERE ProductCrn = @Crn.
        /// </summary>
        public static string ProductDelete {
            get {
                return ResourceManager.GetString("ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to INSERT INTO Product (ProductCrn, Name, Quantity, Price)
        ///VALUES(@Crn, @Name, @Quantity, @Price).
        /// </summary>
        public static string ProductInsert {
            get {
                return ResourceManager.GetString("ProductInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT ProductCrn, Name, Quantity, Price FROM Product WHERE Crn = @crn.
        /// </summary>
        public static string ProductSelectByCrn {
            get {
                return ResourceManager.GetString("ProductSelectByCrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT ProductCrn, Name, Quantity, Price FROM Product.
        /// </summary>
        public static string ProductsSelectAll {
            get {
                return ResourceManager.GetString("ProductsSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UPDATE Product
        ///SET Name = @Name,
        ///Quantity = @Quantity,
        ///Price = @Price
        ///WHERE ProductCrn = @ProductCrn.
        /// </summary>
        public static string ProductUpdate {
            get {
                return ResourceManager.GetString("ProductUpdate", resourceCulture);
            }
        }
    }
}
